
                                 FROM openjdk:22-jdk-slim
                                 WORKDIR /talend
                                 COPY . /talend
                                 CMD ["/bin/bash", "/talend/star_main/star_main_run.sh"]
                                